version: '3.8'
services:
    app:
        build:
            context: . # O Dockerfile está na raiz do projeto
        container_name: formulario_app
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        command: /bin/bash -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm"  # Ajustar permissões antes de rodar o PHP-FPM

    web:
        image: nginx:latest
        container_name: formulario_web
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
